server {
  # Nginx escuchará en el puerto 80 dentro del contenedor
  listen 80;

  # La carpeta raíz donde están tus archivos de la 'build'
  root /usr/share/nginx/html;

  # El archivo principal
  index index.html;

  # Configuración CLAVE para Single Page Applications (SPA)
  location / {
    # Intenta servir el archivo solicitado (ej. /logo192.png)
    # Si no lo encuentra, redirige la petición a /index.html
    # para que React Router pueda manejar la ruta.
    try_files $uri $uri/ /index.html;
  }
}