server {
    listen 80;

    # Bloque para la aplicación estática (HTML, CSS, JS)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Bloque de Proxy para el Backend (Django)
    # CUALQUIER solicitud que empiece con /api/ será REDIRIGIDA al contenedor backend
    location /api/ {
        # 'backend' es el nombre del servicio en el docker-compose.yml
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}