"""
Django settings for misionemprende project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i9#hgunt*zdj*t18&=a!i4w^(9zr4q#wznx0(ze=dndtovl72_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',



    # --- Tus Apps ---
    'rest_framework',
    "rest_framework.authtoken",      
    'corsheaders',          
    'django_extensions',

    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- Configuración de CORS ---
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'misionemprende.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'misionemprende.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'InnovatingTeamsv6',  # El nombre EXACTO de tu base de datos en PostgreSQL
        'USER': 'postgres',       # Tu usuario de PostgreSQL
        'PASSWORD': '123456',   # Tu contraseña de PostgreSQL
        'HOST': 'localhost',                   # O la IP del servidor de BD (usualmente localhost)
        'PORT': '5432',                      # Puerto por defecto de PostgreSQL
    }
}


"""
Si eres otro usuario y necesitas configurar la base de datos SQLite3,
puedes usar la siguiente configuración comentada:

"""

AUTH_USER_MODEL = 'api.Usuario'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""
Configuración para unirse a react
Ya está configurado arriba en CORS_ALLOWED_ORIGINS
"""

# AUTENTICACION DE UNA VEZ POR TODAS


AUTH_USER_MODEL = 'api.Usuario'


# Google Cloud Storage Configuration
import os
from pathlib import Path

# Ruta al archivo de credenciales de Google Cloud
# Puedes colocar tu archivo JSON de credenciales en el directorio backend/
GCS_CREDENTIALS_FILE = os.path.join(BASE_DIR, 'gcs-credentials.json')

# Configuraciones de Google Cloud Storage
# Lee el nombre del bucket y el project id desde variables de entorno cuando sea posible
GCS_BUCKET_NAME = os.getenv('GCS_BUCKET_NAME', 'mision-emprende-prototiposs')  # Tu bucket real
GCS_PROJECT_ID = os.getenv('GCS_PROJECT_ID', 'misionemprende')  # Project ID desde JSON de credenciales
GCS_REGION = os.getenv('GCS_REGION', 'us-central1')  # Región por defecto

# Configuración opcional para URLs firmadas
GCS_SIGNED_URL_EXPIRATION = 3600  # 1 hora en segundos
GCS_PUBLIC_URL_EXPIRATION = 86400  # 24 horas en segundos