# Generated by Django 5.2.7 on 2025-10-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='estudiante',
            table_comment='Información específica de estudiantes',
        ),
        migrations.AlterField(
            model_name='atributo',
            name='categoria_atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaatributo'),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='equipo_desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipodesafio'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.facultad'),
        ),
        migrations.AlterField(
            model_name='configuracionvalor',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracion'),
        ),
        migrations.AlterField(
            model_name='configuracionvalor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.carrera'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipocurso'),
        ),
        migrations.AlterField(
            model_name='cursoestudiante',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='cursoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.persona'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='tema_desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.temadesafio'),
        ),
        migrations.AlterField(
            model_name='equipodesafio',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.desafio'),
        ),
        migrations.AlterField(
            model_name='equipodesafio',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lista_participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.listaparticipante'),
        ),
        migrations.AlterField(
            model_name='evaluacionautoencuesta',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacionautoencuesta',
            name='ganas_emprender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ganasemprender'),
        ),
        migrations.AlterField(
            model_name='evaluacionpitch',
            name='equipo_evaluado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacionpitch_equipo_evaluado_set', to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='evaluacionpitch',
            name='equipo_evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='instruccionetapa',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etapa'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.video'),
        ),
        migrations.AlterField(
            model_name='partidausuario',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='partidausuario',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partida'),
        ),
        migrations.AlterField(
            model_name='partidausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='solucionlego',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='token',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='token',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etapa'),
        ),
    ]
