# Generated by Django 5.2.7 on 2025-11-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contrasena_usuario_password_progresoetapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
