# Generated by Django 5.2.7 on 2025-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaDetalleEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.IntegerField()),
                ('nombreequipo', models.CharField(max_length=100)),
                ('profesor_id', models.IntegerField(blank=True, null=True)),
                ('nombre_profesor', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_profesor', models.CharField(blank=True, max_length=50, null=True)),
                ('email_profesor', models.CharField(blank=True, max_length=100, null=True)),
                ('estudiante_id', models.IntegerField(blank=True, null=True)),
                ('nombre_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('email_estudiante', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_facultad', models.CharField(blank=True, max_length=100, null=True)),
                ('partida_id', models.IntegerField()),
                ('codigoacceso', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vista_detalle_equipo',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='api_usuario',
        ),
    ]
