# Generated by Django 5.2.7 on 2025-11-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vistadetalleequipo_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.video'),
        ),
    ]
