# Generated by Django 5.2.7 on 2025-11-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_partida_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo_equipo',
            field=models.CharField(blank=True, help_text='Código único partida-equipo para acceso del dispositivo', max_length=10, null=True, unique=True),
        ),
    ]
