# Generated by Django 5.2.7 on 2025-11-30 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_equipo_codigo_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ingresado', models.CharField(help_text='Código de 7 dígitos ingresado por el estudiante', max_length=7)),
                ('timestamp_conexion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se conectó')),
                ('activo', models.BooleanField(default=True, help_text='Si está actualmente conectado a la partida')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='api.equipo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='api.partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_partida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conexion_partida',
                'ordering': ['timestamp_conexion'],
                'unique_together': {('partida', 'equipo', 'usuario')},
            },
        ),
    ]
