# Generated by Django 5.2.7 on 2025-11-30 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_conexionpartida'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conexionpartida',
            unique_together={('partida', 'equipo')},
        ),
        migrations.AlterField(
            model_name='conexionpartida',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el equipo está actualmente conectado'),
        ),
        migrations.AlterField(
            model_name='conexionpartida',
            name='codigo_ingresado',
            field=models.CharField(help_text='Código de 7 dígitos ingresado', max_length=7),
        ),
        migrations.AlterField(
            model_name='conexionpartida',
            name='timestamp_conexion',
            field=models.DateTimeField(auto_now_add=True, help_text='Momento en que el equipo se conectó'),
        ),
        migrations.AlterField(
            model_name='conexionpartida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_partida', to=settings.AUTH_USER_MODEL),
        ),
    ]
