# Generated by Django 5.2.7 on 2025-11-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_conexionpartida_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(help_text='Estado actual de la partida (CONFIGURACION, EN_ESPERA, INICIADA, FASE_VIDEO, FASE_1-7, FINALIZADA)', max_length=50)),
                ('fase_actual', models.IntegerField(default=0, help_text='Número de fase actual: 0=espera, 1=video, 2-8=fases 1-7')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Momento del cambio de estado')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Solo el registro activo=True representa el estado actual')),
                ('mensaje', models.CharField(blank=True, help_text='Mensaje opcional para contexto del cambio', max_length=255, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_historial', to='api.partida')),
            ],
            options={
                'db_table': 'estado_partida',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['partida', 'activo'], name='idx_partida_activo'), models.Index(fields=['timestamp'], name='idx_timestamp'), models.Index(fields=['estado_actual'], name='idx_estado')],
            },
        ),
    ]
