# Generated by Django 5.2.7 on 2025-11-05 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'administrador',
                'db_table_comment': 'Informaci�n espec�fica de administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoratributo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'atributo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria_atributo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipodato', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'configuracion_valor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'curso_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nombrepersona', models.CharField(blank=True, max_length=100, null=True)),
                ('edadpersona', models.SmallIntegerField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'desafio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreequipo', models.CharField(max_length=100)),
                ('tamanoequipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'db_table_comment': 'Equipos de estudiantes por juego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'estudiante',
                'db_table_comment': 'Informaci�n espec�fica de estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreetapa', models.CharField(max_length=50)),
                ('duracionminutos', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('textohabilidad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'etapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionAutoencuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evalsatisf', models.SmallIntegerField(blank=True, db_comment='Puntuacion de 1-5, que se mapea con : No, No mucho, M�s o menos, Si, Si, mucho', null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_autoencuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajeequipo', models.SmallIntegerField(blank=True, null=True)),
                ('puntajeempatia', models.SmallIntegerField(blank=True, null=True)),
                ('puntajecreatividad', models.SmallIntegerField(blank=True, null=True)),
                ('puntajecomunicacion', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_pitch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'facultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GanasEmprender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ganas_emprender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstruccionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
            options={
                'db_table': 'instruccion_etapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailestudiante', models.CharField(max_length=100)),
                ('nombreestudiante', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'lista_participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('codigoacceso', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('fechainicio', models.DateTimeField(blank=True, null=True)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('maxequipos', models.IntegerField(blank=True, null=True)),
                ('maxparticipantes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partida',
                'db_table_comment': 'Sesiones de juego del sistema de emprendimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartidaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'partida_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepersona', models.CharField(max_length=150)),
                ('imagenurl', models.CharField(max_length=500)),
                ('contextopersona', models.TextField()),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'profesor',
                'db_table_comment': 'Informaci�n espec�fica de profesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totaltokens', models.IntegerField()),
                ('posicionfinal', models.IntegerField()),
            ],
            options={
                'db_table': 'ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolucionLego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField()),
                ('descripsoluc', models.TextField(blank=True, null=True)),
                ('fotoprototipurl', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'solucion_lego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretema', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tema_desafio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipotoken', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('fechaotorgada', models.DateTimeField()),
            ],
            options={
                'db_table': 'token',
                'db_table_comment': 'Sistema de tokens y recompensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipousuario', models.CharField(max_length=20)),
                ('fechacreacion', models.DateTimeField()),
                ('ultimologin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'db_table_comment': 'Tabla base de usuarios del sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrevideo', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaDetalleEquipo',
            fields=[
                ('equipo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreequipo', models.CharField(max_length=100)),
                ('nombre_profesor', models.CharField(max_length=50)),
                ('email_profesor', models.CharField(max_length=100)),
                ('nombre_estudiante', models.CharField(max_length=50)),
                ('email_estudiante', models.CharField(max_length=100)),
                ('nombre_carrera', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vista_detalle_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoDesafio',
            fields=[
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.equipo')),
                ('desafio_persona_id', models.IntegerField()),
            ],
            options={
                'db_table': 'equipo_desafio',
                'managed': False,
            },
        ),
    ]
