-- =====================================================
-- Script de creación de Base de Datos PostgreSQL
-- Sistema de Emprendimiento
-- Generado: 2025-10-18.
-- Compatible con: PostgreSQL 12+
-- =====================================================

-- =====================================================
-- CREACIÓN DE BASE DE DATOS
-- =====================================================
-- Nota: Ejecutar con usuario con privilegios de creación de BD


-- Conectarse a la base de datos creada

-- =====================================================
-- CREACIÓN DE TABLAS
-- =====================================================

CREATE TABLE ADMINISTRADOR (
    id           SERIAL PRIMARY KEY,
    USUARIO_id   INTEGER NOT NULL
);
COMMENT ON TABLE ADMINISTRADOR IS 'Información específica de administradores';

CREATE TABLE ATRIBUTO (
    id                         SERIAL PRIMARY KEY,
    valorAtributo              VARCHAR(255),
    CATEGORIA_ATRIBUTO_id      INTEGER NOT NULL,
    EQUIPO_DESAFIO_id          INTEGER NOT NULL
);

CREATE TABLE CARRERA (
    id            SERIAL PRIMARY KEY,
    FACULTAD_id   INTEGER NOT NULL,
    nombre        VARCHAR(100) NOT NULL,
    estado        VARCHAR(20) DEFAULT 'ACTIVO'
);
ALTER TABLE CARRERA ADD CONSTRAINT carrera_estado_chk CHECK (estado IN ('ACTIVO', 'INACTIVO'));

CREATE TABLE CATEGORIA_ATRIBUTO (
    id                SERIAL PRIMARY KEY,
    nombreCategoria   VARCHAR(100) NOT NULL
);

CREATE TABLE CONFIGURACION (
    id         SERIAL PRIMARY KEY,
    nombre     VARCHAR(100) NOT NULL,
    tipoDato   VARCHAR(50) NOT NULL
);

CREATE TABLE CONFIGURACION_VALOR (
    id                 SERIAL PRIMARY KEY,
    valor              VARCHAR(500) NOT NULL,
    CONFIGURACION_id   INTEGER NOT NULL,
    USUARIO_id         INTEGER NOT NULL
);

CREATE TABLE CURSO (
    id              SERIAL PRIMARY KEY,
    CARRERA_id      INTEGER NOT NULL,
    TIPO_CURSO_id   INTEGER NOT NULL,
    codigo          VARCHAR(20) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    descripcion     TEXT
);

CREATE TABLE CURSO_ESTUDIANTE (
    id              SERIAL PRIMARY KEY,
    CURSO_id        INTEGER NOT NULL,
    ESTUDIANTE_id   INTEGER NOT NULL
);

CREATE TABLE DESAFIO (
    id                SERIAL NOT NULL,
    TEMA_DESAFIO_id   INTEGER NOT NULL,
    fechaCreacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    titulo            VARCHAR(200) NOT NULL,
    descripcion       TEXT NOT NULL,
    nombrePersona     VARCHAR(100),
    edadPersona       SMALLINT,
    contexto          TEXT,
    estado            VARCHAR(20) DEFAULT 'ACTIVO',
    PERSONA_id        INTEGER NOT NULL,
    PRIMARY KEY (id, PERSONA_id)
);

CREATE TABLE EQUIPO (
    id             SERIAL PRIMARY KEY,
    nombreEquipo   VARCHAR(100) NOT NULL,
    tamanoEquipo   INTEGER
);
COMMENT ON TABLE EQUIPO IS 'Equipos de estudiantes por juego';

CREATE TABLE EQUIPO_DESAFIO (
    EQUIPO_id            INTEGER NOT NULL PRIMARY KEY,
    DESAFIO_id           INTEGER NOT NULL,
    DESAFIO_PERSONA_id   INTEGER NOT NULL
);

CREATE TABLE ESTUDIANTE (
    id                        SERIAL PRIMARY KEY,
    USUARIO_id                INTEGER NOT NULL,
    LISTA_PARTICIPANTE_id     INTEGER NOT NULL
);
COMMENT ON TABLE ESTUDIANTE IS 'Información específica de estudiantes';

CREATE TABLE ETAPA (
    id                SERIAL PRIMARY KEY,
    nombreEtapa       VARCHAR(50) NOT NULL,
    duracionMinutos   INTEGER NOT NULL,
    orden             INTEGER NOT NULL,
    descripcion       VARCHAR(500),
    estado            VARCHAR(20) DEFAULT 'ACTIVO',
    textoHabilidad    VARCHAR(500)
);

CREATE TABLE EVALUACION_AUTOENCUESTA (
    id                    SERIAL PRIMARY KEY,
    ESTUDIANTE_id         INTEGER NOT NULL,
    GANAS_EMPRENDER_id    INTEGER NOT NULL,
    evalSatisf            SMALLINT,
    comentarios           TEXT
);
COMMENT ON COLUMN EVALUACION_AUTOENCUESTA.evalSatisf IS 'Puntuacion de 1-5, que se mapea con : No, No mucho, Más o menos, Si, Si, mucho';
ALTER TABLE EVALUACION_AUTOENCUESTA ADD CONSTRAINT eval_satisf_chk CHECK (evalSatisf BETWEEN 1 AND 5);

CREATE TABLE EVALUACION_PITCH (
    id                    SERIAL PRIMARY KEY,
    EQUIPO_EVALUADOR_id   INTEGER NOT NULL,
    EQUIPO_EVALUADO_id    INTEGER NOT NULL,
    puntajeEquipo         SMALLINT,
    puntajeEmpatia        SMALLINT,
    puntajeCreatividad    SMALLINT,
    puntajeComunicacion   SMALLINT
);
ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT evaluacion_equipo_chk CHECK (puntajeEquipo BETWEEN 1 AND 4);
ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT evaluacion_empatia_chk CHECK (puntajeEmpatia BETWEEN 1 AND 4);
ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT evaluacion_creatividad_chk CHECK (puntajeCreatividad BETWEEN 1 AND 4);
ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT evaluacion_comunicacion_chk CHECK (puntajeComunicacion BETWEEN 1 AND 4);

CREATE TABLE FACULTAD (
    id       SERIAL PRIMARY KEY,
    nombre   VARCHAR(100) NOT NULL
);

CREATE TABLE GANAS_EMPRENDER (
    id            SERIAL PRIMARY KEY,
    descripcion   VARCHAR(500) NOT NULL
);

CREATE TABLE INSTRUCCION_ETAPA (
    id           SERIAL PRIMARY KEY,
    ETAPA_id     INTEGER NOT NULL,
    contenido    TEXT NOT NULL
);

CREATE TABLE LISTA_PARTICIPANTE (
    id                 SERIAL PRIMARY KEY,
    emailEstudiante    VARCHAR(100) NOT NULL,
    nombreEstudiante   VARCHAR(150) NOT NULL
);

CREATE TABLE PARTIDA (
    id                 SERIAL PRIMARY KEY,
    VIDEO_id           INTEGER NOT NULL,
    fechaCreacion      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado             VARCHAR(20) DEFAULT 'CONFIGURACION' NOT NULL,
    codigoAcceso       VARCHAR(10),
    fechaInicio        TIMESTAMP,
    fechaFin           TIMESTAMP,
    maxEquipos         INTEGER DEFAULT 4,
    maxParticipantes   INTEGER
);
ALTER TABLE PARTIDA ADD CONSTRAINT juego_estado_chk CHECK (estado IN ('CONFIGURACION', 'EN_CURSO', 'FINALIZADO'));
COMMENT ON TABLE PARTIDA IS 'Sesiones de juego del sistema de emprendimiento';

CREATE TABLE PARTIDA_USUARIO (
    id           SERIAL PRIMARY KEY,
    USUARIO_id   INTEGER NOT NULL,
    PARTIDA_id   INTEGER NOT NULL,
    EQUIPO_id    INTEGER NOT NULL
);

CREATE TABLE PERSONA (
    id                SERIAL PRIMARY KEY,
    nombrePersona     VARCHAR(150) NOT NULL,
    imagenUrl         VARCHAR(500) NOT NULL,
    contextoPersona   TEXT NOT NULL,
    edad              SMALLINT
);

CREATE TABLE PROFESOR (
    id           SERIAL PRIMARY KEY,
    USUARIO_id   INTEGER NOT NULL
);
COMMENT ON TABLE PROFESOR IS 'Información específica de profesores';

CREATE TABLE RANKING (
    id              SERIAL PRIMARY KEY,
    EQUIPO_id       INTEGER NOT NULL,
    totalTokens     INTEGER DEFAULT 0 NOT NULL,
    posicionFinal   INTEGER NOT NULL
);

CREATE TABLE SOLUCION_LEGO (
    id                SERIAL PRIMARY KEY,
    EQUIPO_id         INTEGER NOT NULL,
    fechaCreacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    descripSoluc      TEXT,
    fotoPrototipUrl   VARCHAR(500)
);

CREATE TABLE TEMA_DESAFIO (
    id            SERIAL PRIMARY KEY,
    nombreTema    VARCHAR(100) NOT NULL,
    descripcion   VARCHAR(500) NOT NULL,
    estado        VARCHAR(20) DEFAULT 'ACTIVO'
);

CREATE TABLE TIPO_CURSO (
    id       SERIAL PRIMARY KEY,
    nombre   VARCHAR(100) NOT NULL
);

CREATE TABLE TOKEN (
    id              SERIAL PRIMARY KEY,
    EQUIPO_id       INTEGER NOT NULL,
    tipoToken       VARCHAR(30) NOT NULL,
    cantidad        INTEGER NOT NULL,
    ETAPA_id        INTEGER,
    fechaOtorgada   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE TOKEN ADD CONSTRAINT token_tipo_chk CHECK (tipoToken IN ('BONIFICACION', 'EVALUACION', 'RECOMPENSA_ETAPA'));
COMMENT ON TABLE TOKEN IS 'Sistema de tokens y recompensas';
COMMENT ON COLUMN TOKEN.id IS 'Esta entidad permite trazabilidad de los tokens ganados por etapas';

CREATE TABLE USUARIO (
    id              SERIAL PRIMARY KEY,
    email           VARCHAR(100) NOT NULL,
    nombre          VARCHAR(50) NOT NULL,
    apellido        VARCHAR(50) NOT NULL,
    tipoUsuario     VARCHAR(20) NOT NULL,
    fechaCreacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ultimoLogin     TIMESTAMP,
    estado          VARCHAR(20) DEFAULT 'ACTIVO',
    contrasena      VARCHAR(255)
);
ALTER TABLE USUARIO ADD CONSTRAINT usuario_tipo_chk CHECK (tipoUsuario IN ('ADMINISTRADOR', 'ESTUDIANTE', 'PROFESOR'));
ALTER TABLE USUARIO ADD CONSTRAINT usuario_estado_chk CHECK (estado IN ('ACTIVO', 'INACTIVO'));
COMMENT ON TABLE USUARIO IS 'Tabla base de usuarios del sistema';

CREATE TABLE VIDEO (
    id            SERIAL PRIMARY KEY,
    nombreVideo   VARCHAR(150) NOT NULL,
    url           VARCHAR(500) NOT NULL
);

-- =====================================================
-- CONSTRAINTS ÚNICOS
-- =====================================================
ALTER TABLE ADMINISTRADOR ADD CONSTRAINT ADMINISTRADOR_idUsuario_UN UNIQUE (USUARIO_id);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT ESTUDIANTE_idUsuario_UN UNIQUE (USUARIO_id);
ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT EVALUACION_PITCH_idEquipEval_UN UNIQUE (EQUIPO_EVALUADOR_id, EQUIPO_EVALUADO_id);
ALTER TABLE PARTIDA ADD CONSTRAINT PARTIDA_codigoAcceso_UN UNIQUE (codigoAcceso);
ALTER TABLE PROFESOR ADD CONSTRAINT PROFESOR_idUsuario_UN UNIQUE (USUARIO_id);
ALTER TABLE RANKING ADD CONSTRAINT RANKING_idEquipo_UN UNIQUE (EQUIPO_id);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_email_UN UNIQUE (email);

-- =====================================================
-- FOREIGN KEYS
-- =====================================================
ALTER TABLE ADMINISTRADOR ADD CONSTRAINT ADMINISTRADOR_USUARIO_FK 
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO (id);

ALTER TABLE ATRIBUTO ADD CONSTRAINT ATRIBUTO_CATEGORIA_ATRIBUTO_FK 
    FOREIGN KEY (CATEGORIA_ATRIBUTO_id) REFERENCES CATEGORIA_ATRIBUTO (id);

ALTER TABLE ATRIBUTO ADD CONSTRAINT ATRIBUTO_EQUIPO_DESAFIO_FK 
    FOREIGN KEY (EQUIPO_DESAFIO_id) REFERENCES EQUIPO_DESAFIO (EQUIPO_id);

ALTER TABLE CARRERA ADD CONSTRAINT CARRERA_FACULTAD_FK 
    FOREIGN KEY (FACULTAD_id) REFERENCES FACULTAD (id);

ALTER TABLE CONFIGURACION_VALOR ADD CONSTRAINT FK_CONFVALOR_CONFIGURACION 
    FOREIGN KEY (CONFIGURACION_id) REFERENCES CONFIGURACION (id);

ALTER TABLE CONFIGURACION_VALOR ADD CONSTRAINT FK_CONFVALOR_USUARIO 
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO (id);

ALTER TABLE CURSO ADD CONSTRAINT CURSO_CARRERA_FK 
    FOREIGN KEY (CARRERA_id) REFERENCES CARRERA (id);

ALTER TABLE CURSO_ESTUDIANTE ADD CONSTRAINT FK_CURSOEST_CURSO 
    FOREIGN KEY (CURSO_id) REFERENCES CURSO (id);

ALTER TABLE CURSO_ESTUDIANTE ADD CONSTRAINT FK_CURSOEST_ESTUDIANTE 
    FOREIGN KEY (ESTUDIANTE_id) REFERENCES ESTUDIANTE (id);

ALTER TABLE CURSO ADD CONSTRAINT CURSO_TIPO_CURSO_FK 
    FOREIGN KEY (TIPO_CURSO_id) REFERENCES TIPO_CURSO (id);

ALTER TABLE DESAFIO ADD CONSTRAINT DESAFIO_PERSONA_FK 
    FOREIGN KEY (PERSONA_id) REFERENCES PERSONA (id);

ALTER TABLE DESAFIO ADD CONSTRAINT DESAFIO_TEMA_DESAFIO_FK 
    FOREIGN KEY (TEMA_DESAFIO_id) REFERENCES TEMA_DESAFIO (id);

ALTER TABLE EQUIPO_DESAFIO ADD CONSTRAINT FK_EQUIPODESAFIO_DESAFIO 
    FOREIGN KEY (DESAFIO_id, DESAFIO_PERSONA_id) REFERENCES DESAFIO (id, PERSONA_id);

ALTER TABLE EQUIPO_DESAFIO ADD CONSTRAINT FK_EQUIPODESAFIO_EQUIPO 
    FOREIGN KEY (EQUIPO_id) REFERENCES EQUIPO (id);

ALTER TABLE ESTUDIANTE ADD CONSTRAINT ESTUDIANTE_LISTA_PARTICIPANTE_FK 
    FOREIGN KEY (LISTA_PARTICIPANTE_id) REFERENCES LISTA_PARTICIPANTE (id);

ALTER TABLE ESTUDIANTE ADD CONSTRAINT ESTUDIANTE_USUARIO_FK 
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO (id);

ALTER TABLE EVALUACION_AUTOENCUESTA ADD CONSTRAINT FK_EVALAUTO_ESTUDIANTE 
    FOREIGN KEY (ESTUDIANTE_id) REFERENCES ESTUDIANTE (id);

ALTER TABLE EVALUACION_AUTOENCUESTA ADD CONSTRAINT FK_EVALAUTO_GANAS 
    FOREIGN KEY (GANAS_EMPRENDER_id) REFERENCES GANAS_EMPRENDER (id);

ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT FK_EVALPITCH_EQUIPO_EVALUADOR 
    FOREIGN KEY (EQUIPO_EVALUADOR_id) REFERENCES EQUIPO (id);

ALTER TABLE EVALUACION_PITCH ADD CONSTRAINT FK_EVALPITCH_EQUIPO_EVALUADO 
    FOREIGN KEY (EQUIPO_EVALUADO_id) REFERENCES EQUIPO (id);

ALTER TABLE INSTRUCCION_ETAPA ADD CONSTRAINT INSTRUCCION_ETAPA_ETAPA_FK 
    FOREIGN KEY (ETAPA_id) REFERENCES ETAPA (id);

ALTER TABLE PARTIDA_USUARIO ADD CONSTRAINT PARTIDA_USUARIO_EQUIPO_FK 
    FOREIGN KEY (EQUIPO_id) REFERENCES EQUIPO (id);

ALTER TABLE PARTIDA_USUARIO ADD CONSTRAINT PARTIDA_USUARIO_PARTIDA_FK 
    FOREIGN KEY (PARTIDA_id) REFERENCES PARTIDA (id);

ALTER TABLE PARTIDA_USUARIO ADD CONSTRAINT PARTIDA_USUARIO_USUARIO_FK 
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO (id);

ALTER TABLE PARTIDA ADD CONSTRAINT PARTIDA_VIDEO_FK 
    FOREIGN KEY (VIDEO_id) REFERENCES VIDEO (id);

ALTER TABLE PROFESOR ADD CONSTRAINT PROFESOR_USUARIO_FK 
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO (id);

ALTER TABLE RANKING ADD CONSTRAINT RANKING_EQUIPO_FK 
    FOREIGN KEY (EQUIPO_id) REFERENCES EQUIPO (id);

ALTER TABLE SOLUCION_LEGO ADD CONSTRAINT SOLUCION_LEGO_EQUIPO_FK 
    FOREIGN KEY (EQUIPO_id) REFERENCES EQUIPO (id);

ALTER TABLE TOKEN ADD CONSTRAINT TOKEN_EQUIPO_FK 
    FOREIGN KEY (EQUIPO_id) REFERENCES EQUIPO (id);

ALTER TABLE TOKEN ADD CONSTRAINT TOKEN_ETAPA_FK 
    FOREIGN KEY (ETAPA_id) REFERENCES ETAPA (id);


-- =====================================================
-- FIN DEL SCRIPT - Creación de tablas
-- =====================================================



